---
output: 
  html_document:
    _disableToc: true
---
<body background="images/drug_opc.jpg">
</body>
<body>
<h2>**Prevention Better than Cure: Drug Overdose Deaths in US**</h2>
<h3>Map and explore drug overdose deaths in the US jurisdictions across years</h3>
<h4>*Jinghan Liu | Paula Wu | Yuxuan Chen | Yuan Meng | Yijia Chen*</h4>
</body>
<br>


```{r setup, include=FALSE}
library(plotly)
library(dplyr)
library(readr)
library(tidyverse)
```
```{r,message=FALSE, warning=FALSE,echo = FALSE}
mine_df = 
  read_csv("./data/usa_99_19.csv") %>% 
  janitor::clean_names() %>%
  filter(!(notes %in% "Total"),
         !(is.na(state))) %>% 
  select(state, year, deaths, population, crude_rate) %>% 
  mutate(state_name= state.abb[match(state, state.name)],
         hover = paste0(state, "\nDeath Crude Rate:", crude_rate),
         crude_rate = as.numeric(crude_rate)) %>% 
  mutate(crude_rate = replace_na(crude_rate, 0))

```

<style>
img {
  display: block;
  margin-left: auto;
  margin-right: auto;
}
</style>
```{r,echo = FALSE, fig.align='center', fig.width=10, fig.height=5.5}
font_style = list(
  size = 15, 
  color = "black"
)
label = list(
  bgcolor = "#EEEEEE",
  bordercolor = "transparent",
  font = font_style
)
death_graph = plot_geo(mine_df, 
                       locationmode = "USA-states",
                       frame = ~year) %>% 
  add_trace(locations = ~state_name,
            z = ~crude_rate,
            zmin = 0,
            zmax = max(pull(mine_df, crude_rate)),
            color = ~crude_rate,
            colorscale = "Blue",
            text = ~hover,
            hoverinfo = "text") %>% 
  layout(geo = list(scope = "usa"),
         title = "\nDeath Rate by State in the US\n1999-2019") %>% 
  style(hoverlabel = label) %>% 
  plotly::config(displayModeBar = FALSE)

death_graph = death_graph %>% 
  animation_button(
    x = 1, xanchor = "right", y = 0, yanchor = "bottom"
  ) %>% animation_opts(
    1000, easing = "elastic", redraw = FALSE
  )
  
death_graph
```



