---
title: "Ohio_data_analyzing"
output: 
  html_document:
    code_folding: hide
    toc: true
    toc_float: true
---

```{r message=FALSE, echo = FALSE}
library(tidyverse)
library(rvest)
library(httr)
library(viridis)
library(plotly)
library(dplyr)
library(readr)
library(maps)
library(choroplethr)
library(choroplethrMaps)
library(patchwork)
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE,
	fig.width = 9, 
  fig.height = 6,
  out.width = "90%"
)
options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d

theme_set(theme_minimal() + theme(legend.position = "bottom"))
```

## Import and Clean data ##

```{r message = FALSE}
drug_overdose = read_csv("./data/VSRR_Provisional_Drug_Overdose_Death_Counts.csv") %>% 
  janitor::clean_names()

state_level = c(state.name[1:8], "District of Columbia", state.name[9:32],"New York City", state.name[33:50])

drug_overdose_52 = 
  drug_overdose %>% 
  filter(!(state_name %in% c("United States"))) %>% 
  relocate(state_name) %>% 
  mutate(month = factor(month, levels = month.name), # change month and year to factor
         year = factor(year),
         state_name = factor(state_name, levels = state_level)) %>% 
  arrange(state_name) %>% 
  group_by(state_name, year) %>% 
  mutate(month = sort(month)) 

drug_overdose_death = 
  drug_overdose_52 %>% 
  select(-c(state, footnote_symbol, percent_complete, period, percent_pending_investigation, predicted_value)) %>% 
  filter(indicator %in% c("Number of Deaths", "Percent with drugs specified", "Number of Drug Overdose Deaths"))
```


```{r echo = FALSE}
drug_categories = 
  drug_overdose_52 %>%
  ungroup() %>% 
  select(-c(state, footnote_symbol, percent_complete, period, percent_pending_investigation, footnote, predicted_value)) %>% 
  filter(str_detect(indicator, "T4"))
```


```{r message=FALSE, echo = FALSE}
# chose the data from 2015 to 2021
# model-based death rate:
predicted_deathrate_bycounty = 
  read_csv("./data/NCHS_-_Drug_Poisoning_Mortality_by_County__United_States.csv") %>% 
  janitor::clean_names() %>% 
  arrange(state) %>% 
  filter(year %in% (2015:2018),
         state %in% "New York")
```

## Ohio part:

```{r}
Ohio_death = 
  drug_overdose_52 %>% 
  filter(state_name %in% "Ohio",
         indicator %in%  c("Number of Deaths", "Number of Drug Overdose Deaths")) %>% 
  select(year, month, indicator, deaths = data_value) %>% 
  pivot_wider(
    names_from = indicator,
    values_from = deaths
  ) %>% 
  janitor::clean_names() %>% 
  group_by(year, month) %>% 
  mutate(
    percent_overdose_death = number_of_drug_overdose_deaths / number_of_deaths
  )%>% 
mutate(year = factor(year))
 
```

**By drug type**


```{r message=FALSE}
Ohio_df = 
  drug_categories %>% 
  filter(state_name %in% c("Ohio")) 
ggplot(Ohio_df, aes(x = indicator, y = data_value, fill = indicator)) +
  geom_violin(alpha = 0.5) +
  scale_x_discrete(labels = c("Psychostimulants \n with abuse potential \n (T43.6)", "Methadone \n (T40.3)", "Natural & \n semi-synthetic  \n opioids \n (T40.2)", "Natural & semi-\n synthetic opioids, \n incl. methadone \n (T40.2, T40.3)", "Heroin \n (T40.1)", "Cocaine \n (T40.5)", "Synthetic opioids, \n excl. \n methadone \n (T40.4)", "Natural, \n semi-synthetic, & \n synthetic opioids, \n incl. methadone \n (T40.2-T40.4)", "Opioids \n (T40.0-T40.4,\n T40.6)")) +
  guides(fill = guide_legend(nrow = 6, byrow = TRUE)) +
  labs(
    title = "OH Number of Drug Overdose Deaths with Drug Categories (2015 - 2021)",
    x = "Drug Categories",
    y = "Number of Drug Overdose Deaths",
    caption = "Data comes from VSRR_Provisional_Drug_Overdose_Death_Counts dataset."
  ) 
```



**By year**


```{r message=FALSE}
death_by_year = 
  drug_overdose_death %>% 
  filter(state_name %in% c("Ohio"), 
         indicator %in% c("Number of Deaths") )

ggplot(death_by_year, aes(x = month, y = data_value, group = year, color = year)) +
    labs(title = "") + 
    geom_line() + 
    geom_point() +
    theme(plot.title = element_text(hjust = 0.5)) +
    scale_x_discrete(labels = c("Psychostimulants \n with abuse potential \n (T43.6)", "Methadone \n (T40.3)", "Natural & \n semi-synthetic  \n opioids \n (T40.2)", "Natural & semi-\n synthetic opioids, \n incl. methadone \n (T40.2, T40.3)", "Heroin \n (T40.1)", "Cocaine \n (T40.5)", "Synthetic opioids, \n excl. \n methadone \n (T40.4)", "Natural, \n semi-synthetic, & \n synthetic opioids, \n incl. methadone \n (T40.2-T40.4)", "Opioids \n (T40.0-T40.4,\n T40.6)")) +
  guides(fill = guide_legend(nrow = 6, byrow = TRUE)) +
    labs(
      title = "Number of Drug Overdose Deaths with Drug Categories by Year in Ohio",
      x = "Month",
      y = "Number of Drug Overdose Deaths",
    caption = "Data comes from VSRR_Provisional_Drug_Overdose_Death_Counts dataset between 2015 and 2021."
  )
```

**Each month Death Within a Year**

```{r message=FALSE}
death_by_year = 
  drug_overdose_death %>% 
  filter(state_name %in% c("Ohio"), 
         indicator %in% c("Number of Deaths") )

ggplot(death_by_year, aes(x = month, y = data_value, group = year, color = year)) +
    labs(title = "") + 
    geom_line() + 
    geom_point() +
    facet_grid(.~year) +
  
    labs(
      title = "Number of Drug Overdose Deaths with Drug Categories by Year in CA",
      x = "Month",
      y = "Number of Drug Overdose Deaths",
    caption = "Data comes from VSRR_Provisional_Drug_Overdose_Death_Counts dataset between 2015 and 2021."
  ) +
    theme(axis.text.x = element_text(angle = 90, hjust = 1)) 
```

```{r message=FALSE, echo = FALSE}
  Ohio_df %>%
  filter(year %in% (2019:2021))  %>%
  ggplot(aes(x = year, y = data_value, color = indicator)) +
  geom_smooth(aes(group = indicator), se = FALSE) +
  scale_color_viridis(discrete = TRUE, labels = c("Psychostimulants with abuse potential (T43.6)", "Methadone (T40.3)", "Natural & semi-synthetic opioids (T40.2)", "Natural & semi-synthetic opioids, incl. methadone (T40.2, T40.3)", "Heroin (T40.1)", "Cocaine (T40.5)", "Synthetic opioids, excl. methadone (T40.4)", "Natural, semi-synthetic, & synthetic opioids, incl. methadone (T40.2-T40.4)", "Opioids (T40.0-T40.4,T40.6)")) +
  guides(color = guide_legend(nrow = 6, byrow = TRUE)) +
  labs(
    title = "Number of Drug Overdose Deaths with Drug Categories by Year in Ohio",
    x = "Year",
    y = "Number of Drug Overdose Deaths",
    caption = "Data comes from VSRR_Provisional_Drug_Overdose_Death_Counts dataset between 2015 and 2021."
  )
```


**Number of death vs median household income**


```{r message=FALSE}
OH_income_df = 
  read_csv("./data/Median_Household_Income_OH.csv") %>% 
  janitor::clean_names() %>% 
  select(year, household_income_by_race, household_income_by_race_moe, geography) %>% 
  filter(str_detect(geography,"OH|Ohio|United States"),
    year >= "2015") %>% 
  mutate(year = factor(year))

OH_income_df %>% 
  mutate(text_label = str_c("Year: ", year, "\nMedian Household Income: $", household_income_by_race, 
                            "\nMargin of error: ± $", household_income_by_race_moe)) %>% 
   plot_ly(
    x = ~year, y = ~household_income_by_race, color = ~geography, text = ~text_label, 
    alpha = 0.5, type = "scatter", mode = "markers+lines", colors = "viridis", error_y = ~list(array = household_income_by_race_moe)) %>% 
  layout(
    title = "Median Household Income: OH vs. The U.S",
         xaxis = list(title = "Year"),
         yaxis = list(title = "Median Household Income"))
```

**Overdose death by age**

```{r message=FALSE}
ca_death_by_age = 
  read_csv("./data/agegroup_race_state_year_99-19.csv") %>%
  janitor::clean_names() %>% 
  select(state, year, ten_year_age_groups, race, deaths, population) %>% 
  filter(state %in% c("Ohio")) %>% 
  mutate(year = factor(year),
         crude_rate = deaths/population * 100000)
  
ca_death_by_age %>% 
  mutate(ten_year_age_groups = gsub("years", "", ten_year_age_groups)) %>% 
  ggplot(aes(x = ten_year_age_groups , y = crude_rate, fill = race)) + 
  geom_boxplot(alpha = 0.5)+
  facet_grid(~race)+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.4, hjust = 1))
```


## Income

**Income and drug overdose death percent by year**

```{r}
OHincome_drug_df = 
  Ohio_death %>% 
  ungroup() %>% 
  group_by(year) %>% 
  summarize(overdose_death_rate = sum(number_of_drug_overdose_deaths)/sum(number_of_deaths)) %>% 
  inner_join(., OH_income_df %>% filter(geography %in% "Ohio"))

year_death = 
  OHincome_drug_df %>% 
  ggplot(aes(x = year, y = overdose_death_rate, group = NA))+
  geom_point()+
  geom_line()
income_year = 
  OHincome_drug_df %>% 
  ggplot(aes(x = year, y = household_income_by_race, group = NA))+
  geom_point()+
  geom_line()

smooth = 
  OHincome_drug_df %>% 
  ggplot(aes(x = household_income_by_race, y = overdose_death_rate, group = NA))+
  geom_point()+
  geom_smooth(method = "lm", se = FALSE, color = "royalblue4")
(year_death + income_year)/smooth
```



**OH Drug Map** 

```{r message=FALSE}
oh_county_df = 
  read_csv("./data/NCHS_-_Drug_Poisoning_Mortality_by_County__United_States.csv") %>% 
  janitor::clean_names() %>% 
  filter(state %in% "Ohio") %>% 
  select(year, county, population, death_rate = model_based_death_rate) %>% 
  separate(county, into = c("county", "useless"), sep = " County") %>% 
  select(-useless) %>% 
  mutate(year = factor(year),
         county = str_to_lower(county)) %>% 
  relocate(county)
oh_county_df
```

```{r, message=FALSE, warning=FALSE,echo=FALSE}
highlight_county = function(county_fips)
{
  data(county.map, package="choroplethrMaps", envir=environment())
  df = county.map[county.map$region %in% county_fips, ]
  geom_polygon(data=df, aes(long, lat, group = group), color = "yellow", fill = NA, size = 1)
}
add_text_county = function(county_fips){
  data(county.map, package="choroplethrMaps", envir=environment())
  df = county.map[county.map$region %in% county_fips, ]
  #geom_text(data=df, aes(mean(long), mean(lat), label = paste0(str_to_title(pull(county_fips, county)), " County\n", pull(county_fips, death_rate))), color = "white")
  geom_label(data=df, aes(mean(long), mean(lat), label = paste0(str_to_title(pull(county_fips, county)), " County\nDR: ", round(pull(county_fips, death_rate),2))), fill = "white", size = 2.5)
}
```
```{r, message=FALSE, warning=FALSE}
data(county.fips)
abc = county.fips %>% 
  separate(polyname, into = c("state", "county"), sep = "\\,") %>% 
  filter(state %in% "ohio") %>% 
  select(-state) %>% 
  as_tibble()
```

### Counties change, 5-yr interval{.tabset}

#### 2003
```{r, message=FALSE, warning=FALSE}
year_select = 2003
start_county_df = left_join(oh_county_df ,abc, by = "county") %>% 
  select(county, year, death_rate, fips) %>% 
  filter(year == year_select)


start_county_df %>% 
  group_by(fips) %>% 
  mutate(fips = as.numeric(fips)) %>% 
  rename(region = fips,
         value = death_rate) %>% 
  county_choropleth(state_zoom = c("ohio"),
                     legend = "death_rate")+
  highlight_county(start_county_df[which.max(pull(start_county_df, death_rate)),])+
  add_text_county(start_county_df[which.max(pull(start_county_df, death_rate)),])
```

#### 2008
```{r, message=FALSE, warning=FALSE}
year_select = 2008
start_county_df = left_join(oh_county_df,abc, by = "county") %>% 
  select(county, year, death_rate, fips) %>% 
  filter(year == year_select)

start_county_df %>% 
  group_by(fips) %>% 
  mutate(fips = as.numeric(fips)) %>% 
  rename(region = fips,
         value = death_rate) %>% 
  county_choropleth(state_zoom = c("ohio"),
                     legend = "death_rate")+
  highlight_county(start_county_df[which.max(pull(start_county_df, death_rate)),])+
  add_text_county(start_county_df[which.max(pull(start_county_df, death_rate)),])
```

#### 2013
```{r, message=FALSE, warning=FALSE}
year_select = 2013

start_county_df = left_join(oh_county_df,abc, by = "county") %>% 
  select(county, year, death_rate, fips) %>% 
  filter(year == year_select)


start_county_df %>% 
  group_by(fips) %>% 
  mutate(fips = as.numeric(fips)) %>% 
  rename(region = fips,
         value = death_rate) %>% 
  county_choropleth(state_zoom = c("ohio"),
                     legend = "death_rate")+
  highlight_county(start_county_df[which.max(pull(start_county_df, death_rate)),])+
  add_text_county(start_county_df[which.max(pull(start_county_df, death_rate)),])
```

#### 2018
```{r, message=FALSE, warning=FALSE, echo=FALSE}
year_select = 2018
start_county_df = left_join(oh_county_df,abc, by = "county") %>% 
  select(county, year, death_rate, fips) %>% 
  filter(year == year_select)


start_county_df %>% 
  group_by(fips) %>% 
  mutate(fips = as.numeric(fips)) %>% 
  rename(region = fips,
         value = death_rate) %>% 
  county_choropleth(state_zoom = c("ohio"),
                     legend = "death_rate")+
  highlight_county(start_county_df[which.max(pull(start_county_df, death_rate)),])+
  add_text_county(start_county_df[which.max(pull(start_county_df, death_rate)),])
```

Back to [homepage](index.html)