---
title: "Shiny Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(viridis)
library(plotly)
library(shiny)
library(lubridate)
library(maps)
library(choroplethr)
library(choroplethrMaps)
data(county.fips)
```

```{r data_import}
drug_overdose = 
  read_csv("./data/VSRR_Provisional_Drug_Overdose_Death_Counts.csv") %>% 
  janitor::clean_names()
state_level = 
  c(state.name[1:8], "District of Columbia", state.name[9:32],"New York City", state.name[33:50])

drug_overdose_52 = 
  drug_overdose %>% 
  filter(!(state_name %in% c("United States"))) %>% 
  relocate(state_name) %>% 
  mutate(month = factor(month, levels = month.name), # change month and year to factor
         year = factor(year),
         state_name = factor(state_name, levels = state_level)) %>% 
  arrange(state_name) %>% 
  select(year, state_name, indicator, deaths = predicted_value, footnote) %>% 
  filter(str_detect(indicator, "T4")) %>% 
 mutate(state= state.abb[match(state_name, state.name)],
         hover = paste0(state_name, "\nDeath:", deaths)) %>%
  filter(!is.na(deaths))

#for barplot
age_race_death = read_csv("./data/agegroup_race_state_year_99-19.csv") %>% 
  janitor::clean_names() %>% 
  select(state, year = year_code, age = ten_year_age_groups_code, race, deaths,population) %>% 
  drop_na() 



# for counties
county_df = 
  read_csv("./data/NCHS_-_Drug_Poisoning_Mortality_by_County__United_States.csv") %>% 
  janitor::clean_names()
```

```{r funcion_setup_counties}
highlight_county = function(county_fips)
{
  data(county.map, package="choroplethrMaps", envir=environment())
  df = county.map[county.map$region %in% county_fips, ]
  geom_polygon(data=df, aes(long, lat, group = group), color = "yellow", fill = NA, size = 1)
}
add_text_county = function(county_fips){
  data(county.map, package="choroplethrMaps", envir=environment())
  df = county.map[county.map$region %in% county_fips, ]
  #geom_text(data=df, aes(mean(long), mean(lat), label = paste0(str_to_title(pull(county_fips, county)), " County\n", pull(county_fips, death_rate))), color = "white")
  geom_label(data=df, aes(mean(long), mean(lat), label = paste0(str_to_title(pull(county_fips, county)), " County\nDR: ", round(pull(county_fips, death_rate),2))), fill = "white", size = 3)
}
```


US drug overdoes death Map
===================================== 


Column {.sidebar}
-----------------------------------------------------------------------

```{r}
# selection from
drug_choice = 
  drug_overdose_52 %>% 
  distinct(indicator) %>% 
  pull()

year = c(2015, 2018:2021)


#state select box
selectInput(
  "drug_type", 
  label = h3("Choose Indicator"),
  choices = drug_choice,
  selected = "Heroin (T40.1)")

# year select box 
selectInput("year", label = h3("Choose year"),
						choices = as.list(year),
						selected = "2018")
```

Column {.tabset}
-----------------------------------------------------------------------

### US MAP

```{r}
renderPlotly({
  font_style = list(
  size = 15, 
  color = "black"
)
label = list(
  bgcolor = "#EEEEEE",
  bordercolor = "transparent",
  font = font_style
)

graph_df = drug_overdose_52 %>% 
  filter(year == input$year) %>% 
  filter(indicator %in% input$drug_type)

plot_geo(graph_df, 
         locationmode = "USA-states") %>% 
  add_trace(locations = ~state,
            z = ~deaths,
            color = ~deaths,
            colorscale = "Blue",
            text = ~hover,
            hoverinfo = "text") %>% 
  layout(geo = list(scope = "usa"),
         title = "Death by state in the US\n2015-2021") %>% 
  style(hoverlabel = label)

})
```


Death by Age and Race
===================================== 

Column {.sidebar}
-----------------------------------------------------------------------

```{r}
year = c(1999:2021)

selectInput("year2", 
            label = h3("Choose year"),
						choices = as.list(year),
						selected = 2015)
```

Column {.tabset}
-----------------------------------------------------------------------

### Drug Overdoes Death Across All States by Age Group and Race

```{r barplot_age_race}

# plot barplot
renderPlotly({
  ar = 
    age_race_death %>% 
  filter(year == input$year2) %>% 
	group_by(age, race) %>%
	summarize(total_deaths = sum(deaths),
	          total_population = sum(population)) %>% 
	mutate(crude_rate = (total_deaths/total_population) * 100000) %>% 
  spread(key = race, value = crude_rate) %>%
  janitor::clean_names() %>% 
  # barplot
  plot_ly(x = ~age,
  				y = ~white,
  				name = "White",
  				type = "bar") %>% 
    	add_trace(y = ~black_or_african_american,
  						name = "Black or African American") %>%
  	add_trace(y = ~asian_or_pacific_islander,
  						name = "Asian or Pacific Islander") %>% 
  	add_trace(y = ~american_indian_or_alaska_native,
  						name = "American Indian or Alaska Native") %>% 
  	layout(barmode = "stack",
  				 xaxis = list(title = "Age Groups"),
  				 yaxis = list(title = "Crude Rate")
  				 )

})


```

County/Borough Death Rates - States/City of Choice
===================================== 

Column {.sidebar}
-----------------------------------------------------------------------

```{r}
# selection from
state_list = c("California", "Florida", "Ohio", "New York City")


year = c(2003:2018)


#state select box
selectInput(
  "state1", 
  label = h3("Choose State"),
  choices = state_list,
  selected = "California")

# year select box 
selectInput("year3", label = h3("Choose year"),
						choices = as.list(year),
						selected = "2015")
```

Column {.tabset}
-----------------------------------------------------------------------

### Drug Overdoes Death Across Counties/Borough within States/City of Choice

```{r}
renderPlot({
  state_input = input$state1
  year_input = input$year3

if (state_input != "New York City") {
  some_county_df = 
    county_df %>%
    filter(state %in% state_input) %>% 
    select(year, county, population, death_rate = model_based_death_rate) %>% 
    separate(county, into = c("county", "useless"), sep = " County") %>% 
    select(-useless) %>% 
    mutate(year = factor(year),
           county = str_to_lower(county)) %>% 
    relocate(county)
  
  abc = county.fips %>% 
    separate(polyname, into = c("state", "county"), sep = "\\,") %>% 
    filter(state %in% str_to_lower(state_input)) %>% 
    select(-state) %>% 
    as.tibble()
  
  some_county_df = left_join(some_county_df,abc, by = "county") %>% 
    select(county, year, death_rate, fips) %>% 
    filter(year == year_input)
  if(state_input %in% "Florida"){
    some_county_df[13,4] = 12027
    some_county_df[46,4] = 12091
    some_county_df[55,4] = 12109
    some_county_df[56,4] = 12111
  }
  some_county_df %>% 
    group_by(fips) %>% 
    mutate(fips = as.numeric(fips)) %>% 
    rename(region = fips,
           value = death_rate) %>% 
    county_choropleth(state_zoom = c(str_to_lower(state_input)), legend = "death_rate")+
    highlight_county(some_county_df[which.max(pull(some_county_df, death_rate)),])+
    add_text_county(some_county_df[which.max(pull(some_county_df, death_rate)),])
}
  else {
  nyc_fip = county.fips %>% 
    filter(str_detect(polyname, "new york")) %>% 
    mutate(
      polyname = str_replace(polyname, "new york,", "")) %>% 
    filter(str_detect(polyname, "bronx|queens|kings|new york|richmond")) %>% 
    as.tibble() %>% 
    slice(rep(1:n(), each = 16)) %>% 
    select(fips)
  
  ny_county_df = 
    county_df %>%
    filter(state %in% "New York") %>% 
    select(year, county, population, death_rate = model_based_death_rate) %>% 
    mutate(
      county = str_replace(county, "County, NY", "")) %>% 
    mutate(year = factor(year),
           county = str_to_lower(county)) %>% 
    filter(str_detect(county, "bronx|queens|kings|new york|richmond")) %>% 
    relocate(county) %>% 
    bind_cols(., nyc_fip) %>% 
    select(county, year, death_rate, fips) %>% 
    filter(year == year_input)
    
  ny_deathrate = 
    ny_county_df %>%
    rename(region = fips,
           value = death_rate) %>% 
    select(value, region)  
    
  county_choropleth(ny_deathrate, title = "Death rates of Counties in New York City",
                      legend = "Death rates",
                      county_zoom = ny_deathrate$region) +
  highlight_county(ny_county_df[which.max(pull(ny_county_df, death_rate)),]) +
  add_text_county(ny_county_df[which.max(pull(ny_county_df, death_rate)),])
}
  
})
```

