```{r, message=FALSE, warning=FALSE}
library(plotly)
library(dplyr)
library(readr)
```
```{r}
mine_df = 
  read_csv("./data/VSRR_Provisional_Drug_Overdose_Death_Counts.csv") %>% 
  janitor::clean_names() %>%
  filter(!(state_name %in% c("New York City", "United States"))) %>% 
  select(year, state_name, indicator, deaths = data_value) %>% 
  filter(indicator %in% "Number of Deaths") %>% 
  mutate(state= state.abb[match(state_name, state.name)],
         hover = paste0(state_name, "\nDeath:", deaths))
mine_df
```
```{r}
font_style = list(
  size = 15, 
  color = "black"
)
label = list(
  bgcolor = "#EEEEEE",
  bordercolor = "transparent",
  font = font_style
)
death_graph = plot_geo(mine_df, 
                       locationmode = "USA-states",
                       frame = ~year) %>% 
  add_trace(locations = ~state,
            z = ~deaths,
            zmin = 0,
            zmax = max(pull(mine_df, deaths)),
            color = ~deaths,
            colorscale = "Electric",
            text = ~hover,
            hoverinfo = "text") %>% 
  layout(geo = list(scope = "usa"),
         title = "Death by state in the US\n2015-2021") %>% 
  style(hoverlabel = label) %>% 
  config(displayModeBar = FALSE)
death_graph
```


